/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import javax.swing.JOptionPane;
import simulator.Memoria;
import simulator.Registrador;
import simulator.UC;

/**
 *
 * @author Thiago
 */
public class Tela extends javax.swing.JFrame {

    String opcode;
    String in1;
    String in2;
    String in3;
    String in4;
    String in5;
    String in6;
    int j, k, l, programCounter;
    String[] textoSeparado;
    boolean pipeline;
    Registrador aux1;
    Registrador aux2;
    Registrador aux3;
    Registrador aux4;
    Registrador aux5;
    Registrador aux6;

    Memoria memoria;
    UC uc;
    Registrador $zero;
    Registrador $at;
    Registrador $v0;
    Registrador $v1;
    Registrador $a0;
    Registrador $a1;
    Registrador $a2;
    Registrador $a3;
    Registrador $t0;
    Registrador $t1;
    Registrador $t2;
    Registrador $t3;
    Registrador $t4;
    Registrador $t5;
    Registrador $t6;
    Registrador $t7;
    Registrador $s0;
    Registrador $s1;
    Registrador $s2;
    Registrador $s3;
    Registrador $s4;
    Registrador $s5;
    Registrador $s6;
    Registrador $s7;
    Registrador $t8;
    Registrador $t9;
    Registrador $k0;
    Registrador $k1;
    Registrador $gp;
    Registrador $sp;
    Registrador $fp;
    Registrador $ra;

    /**
     * Creates new form Tela
     */
    public Tela() {
        programCounter = 0;
        memoria = new Memoria();
        uc = new UC(memoria);
        $zero = new Registrador("$zero", memoria);
        $at = new Registrador("$at", memoria);
        $v0 = new Registrador("$v0", memoria);
        $v1 = new Registrador("$v1", memoria);
        $a0 = new Registrador("$a0", memoria);
        $a1 = new Registrador("$a1", memoria);
        $a2 = new Registrador("$a2", memoria);
        $a3 = new Registrador("$a3", memoria);
        $t0 = new Registrador("$t0", memoria);
        $t1 = new Registrador("$t1", memoria);
        $t2 = new Registrador("$t2", memoria);
        $t3 = new Registrador("$t3", memoria);
        $t4 = new Registrador("$t4", memoria);
        $t5 = new Registrador("$t5", memoria);
        $t6 = new Registrador("$t6", memoria);
        $t7 = new Registrador("$t7", memoria);
        $s0 = new Registrador("$s0", memoria);
        $s1 = new Registrador("$s1", memoria);
        $s2 = new Registrador("$s2", memoria);
        $s3 = new Registrador("$s3", memoria);
        $s4 = new Registrador("$s4", memoria);
        $s5 = new Registrador("$s5", memoria);
        $s6 = new Registrador("$s6", memoria);
        $s7 = new Registrador("$s7", memoria);
        $t8 = new Registrador("$t8", memoria);
        $t9 = new Registrador("$t9", memoria);
        $k0 = new Registrador("$k0", memoria);
        $k1 = new Registrador("$k1", memoria);
        $gp = new Registrador("$gp", memoria);
        $sp = new Registrador("$sp", memoria);
        $fp = new Registrador("$fp", memoria);
        $ra = new Registrador("$ra", memoria);
        pipeline = false;

        aux1 = new Registrador("aux1", memoria);
        aux2 = new Registrador("aux2", memoria);
        aux3 = new Registrador("aux3", memoria);
        aux4 = new Registrador("aux4", memoria);
        aux5 = new Registrador("aux5", memoria);
        aux6 = new Registrador("aux6", memoria);

        initComponents();

        memoria.store(0, 10);
        memoria.store(1, 20);
        memoria.store(2, 30);
        memoria.store(3, 40);
        memoria.store(4, 5);
        memoria.store(5, 2);
        memoria.store(6, 7);

        atualizarTela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel33 = new javax.swing.JLabel();
        r0 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        r16 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        r17 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        r1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        r18 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        r19 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        r3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        r2 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        r20 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        r21 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        r5 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        r4 = new javax.swing.JTextField();
        r22 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        r23 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        r7 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        r6 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        r24 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        r25 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        r9 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        r8 = new javax.swing.JTextField();
        r26 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        r27 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        r11 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        r10 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        r28 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        r29 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        r13 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        r12 = new javax.swing.JTextField();
        r30 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        r31 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        r15 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        r14 = new javax.swing.JTextField();
        textoEntrada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nm1 = new javax.swing.JTextField();
        m0 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        n2m = new javax.swing.JTextField();
        m1 = new javax.swing.JTextField();
        nm6 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        m8 = new javax.swing.JTextField();
        m3 = new javax.swing.JTextField();
        m10 = new javax.swing.JTextField();
        m4 = new javax.swing.JTextField();
        m12 = new javax.swing.JTextField();
        m5 = new javax.swing.JTextField();
        m14 = new javax.swing.JTextField();
        m6 = new javax.swing.JTextField();
        m15 = new javax.swing.JTextField();
        ac = new javax.swing.JTextField();
        checkBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        m16 = new javax.swing.JTextField();
        pc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel33.setText("$zero");

        r0.setEditable(false);

        jLabel34.setText("$s0");

        r16.setEditable(false);

        jLabel35.setText("$s1");

        r17.setEditable(false);

        jLabel36.setText("$at");

        r1.setEditable(false);

        jLabel37.setText("$s2");

        r18.setEditable(false);

        jLabel38.setText("$s3");

        r19.setEditable(false);

        jLabel39.setText("$v1");

        r3.setEditable(false);

        jLabel40.setText("$v0");

        r2.setEditable(false);

        jLabel41.setText("$s4");

        r20.setEditable(false);

        jLabel42.setText("$s5");

        r21.setEditable(false);

        jLabel43.setText("$a1");

        r5.setEditable(false);

        jLabel44.setText("$s6");

        jLabel45.setText("$a0");

        r4.setEditable(false);

        r22.setEditable(false);

        jLabel46.setText("$s7");

        r23.setEditable(false);

        jLabel47.setText("$a3");

        r7.setEditable(false);

        jLabel48.setText("$a2");

        r6.setEditable(false);

        jLabel49.setText("$t8");

        r24.setEditable(false);

        jLabel50.setText("$t9");

        r25.setEditable(false);

        jLabel51.setText("$t1");

        r9.setEditable(false);

        jLabel52.setText("$k0");

        jLabel53.setText("$t0");

        r8.setEditable(false);

        r26.setEditable(false);

        jLabel54.setText("$k1");

        r27.setEditable(false);

        jLabel55.setText("$t3");

        r11.setEditable(false);

        jLabel56.setText("$t2");

        r10.setEditable(false);

        jLabel57.setText("$gp");

        r28.setEditable(false);

        jLabel58.setText("$sp");

        r29.setEditable(false);

        jLabel59.setText("$t5");

        r13.setEditable(false);

        jLabel60.setText("$sp");

        jLabel61.setText("$t4");

        r12.setEditable(false);

        r30.setEditable(false);

        jLabel62.setText("$ra");

        r31.setEditable(false);

        jLabel63.setText("$t7");

        r15.setEditable(false);

        jLabel64.setText("$t6");

        r14.setEditable(false);

        textoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEntradaActionPerformed(evt);
            }
        });

        jLabel1.setText("REGISTRADORES");

        jLabel2.setText("MEMÓRIA");

        Nm1.setEditable(false);
        Nm1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Nm1.setText("End. 0");
        Nm1.setToolTipText("");

        m0.setEditable(false);
        m0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("ENTRADA");

        n2m.setEditable(false);
        n2m.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        n2m.setText("End. 1");

        m1.setEditable(false);
        m1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        nm6.setEditable(false);
        nm6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nm6.setText("End. 2");

        m2.setEditable(false);
        m2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        m8.setEditable(false);
        m8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m8.setText("End. 3");

        m3.setEditable(false);
        m3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        m10.setEditable(false);
        m10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m10.setText("End. 4");

        m4.setEditable(false);
        m4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        m12.setEditable(false);
        m12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m12.setText("End. 5");

        m5.setEditable(false);
        m5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        m14.setEditable(false);
        m14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m14.setText("End. 6");

        m6.setEditable(false);
        m6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        m15.setEditable(false);
        m15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m15.setText("AC");

        ac.setEditable(false);
        ac.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        checkBox.setText("ATIVAR PIPELINE");
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("load nome_registrador, endMemoria\nstore store nome_registrador, endMemoria\n\nadd, sub, mult e div:\nadd reg_salvar, reg_source1, reg_source2");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel5.setText("INSTRUÇÕES");

        m16.setEditable(false);
        m16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        m16.setText("PC");
        m16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m16ActionPerformed(evt);
            }
        });

        pc.setEditable(false);
        pc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkBox, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(91, 91, 91))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(Nm1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(m0, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(n2m, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(nm6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(m8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(m5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(m6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(27, 27, 27)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(91, 91, 91)
                                    .addComponent(jLabel3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(m15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(m16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel61, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel53, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r29, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r30, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(r15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel33)
                            .addComponent(r0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34)
                            .addComponent(r16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel35)
                            .addComponent(r17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel37)
                            .addComponent(r18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)
                            .addComponent(r2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel38)
                            .addComponent(r19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(r3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel41)
                            .addComponent(r20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45)
                            .addComponent(r4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel42)
                            .addComponent(r21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43)
                            .addComponent(r5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel44)
                            .addComponent(r22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48)
                            .addComponent(r6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel46)
                            .addComponent(r23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel47)
                            .addComponent(r7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel49)
                            .addComponent(r24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53)
                            .addComponent(r8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel50)
                            .addComponent(r25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51)
                            .addComponent(r9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n2m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nm6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel52)
                            .addComponent(r26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel56)
                            .addComponent(r10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(m15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel54)
                    .addComponent(r27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(r11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel57)
                            .addComponent(r28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel61)
                            .addComponent(r12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel58)
                            .addComponent(r29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel59)
                            .addComponent(r13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel60)
                            .addComponent(r30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel64)
                            .addComponent(r14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel62)
                            .addComponent(r31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel63)
                            .addComponent(r15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        r0.getAccessibleContext().setAccessibleName("r0");
        r16.getAccessibleContext().setAccessibleName("r16");
        r17.getAccessibleContext().setAccessibleName("r17");
        r1.getAccessibleContext().setAccessibleName("r1");
        r18.getAccessibleContext().setAccessibleName("r18");
        r19.getAccessibleContext().setAccessibleName("r19");
        r3.getAccessibleContext().setAccessibleName("r3");
        r2.getAccessibleContext().setAccessibleName("r2");
        r20.getAccessibleContext().setAccessibleName("r20");
        r21.getAccessibleContext().setAccessibleName("r21");
        r5.getAccessibleContext().setAccessibleName("r5");
        r4.getAccessibleContext().setAccessibleName("r4");
        r22.getAccessibleContext().setAccessibleName("r22");
        r23.getAccessibleContext().setAccessibleName("r23");
        r7.getAccessibleContext().setAccessibleName("r7");
        r6.getAccessibleContext().setAccessibleName("r6");
        r24.getAccessibleContext().setAccessibleName("r24");
        r25.getAccessibleContext().setAccessibleName("r25");
        r9.getAccessibleContext().setAccessibleName("r9");
        r8.getAccessibleContext().setAccessibleName("r8");
        r26.getAccessibleContext().setAccessibleName("r26");
        r27.getAccessibleContext().setAccessibleName("r27");
        r11.getAccessibleContext().setAccessibleName("r11");
        r10.getAccessibleContext().setAccessibleName("r10");
        r28.getAccessibleContext().setAccessibleName("r28");
        r29.getAccessibleContext().setAccessibleName("r29");
        r13.getAccessibleContext().setAccessibleName("r13");
        r12.getAccessibleContext().setAccessibleName("r12");
        r30.getAccessibleContext().setAccessibleName("r30");
        r31.getAccessibleContext().setAccessibleName("r31");
        r15.getAccessibleContext().setAccessibleName("r15");
        r14.getAccessibleContext().setAccessibleName("r14");
        textoEntrada.getAccessibleContext().setAccessibleName("textoEntrada");
        Nm1.getAccessibleContext().setAccessibleName("nm1");
        m0.getAccessibleContext().setAccessibleName("m0");
        n2m.getAccessibleContext().setAccessibleName("nm2");
        ac.getAccessibleContext().setAccessibleName("ac");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEntradaActionPerformed
        textoSeparado = textoEntrada.getText().split(" ");
        opcode = textoSeparado[0];

        try {
            in1 = textoSeparado[1];
            if (in1.contains(",")) {
                if (in1.length() > 0) {
                    in1 = in1.substring(0, in1.length() - 1);
                }
            }

            in2 = textoSeparado[2];
            if (in2.contains(",")) {
                if (in2.length() > 0) {
                    in2 = in2.substring(0, in2.length() - 1);
                }
            }
            in3 = textoSeparado[3];
            if (in3.contains(",")) {
                if (in3.length() > 0) {
                    in3 = in3.substring(0, in3.length() - 1);
                }
            }
            in4 = textoSeparado[4];
            if (in4.contains(",")) {
                if (in4.length() > 0) {
                    in4 = in4.substring(0, in4.length() - 1);
                }
            }
            in5 = textoSeparado[5];
            if (in5.contains(",")) {
                if (in5.length() > 0) {
                    in5 = in5.substring(0, in5.length() - 1);
                }
            }
            in6 = textoSeparado[6];
            if (in6.contains(",")) {
                if (in6.length() > 0) {
                    in6 = in6.substring(0, in6.length() - 1);
                }
            }

        } catch (Exception e) {

        } finally {

            if ((opcode != null && in1 != null && in2 == null && in3 == null) || (opcode != null && in1 != null && in2 != null && in3 == null)) {
                if (in1.equals($zero.getNome())) {
                    j = 0;
                    aux1 = $zero;
                }
                if (in1.equals($at.getNome())) {
                    j = 1;
                    aux1 = $at;
                }
                if (in1.equals($v0.getNome())) {
                    j = 2;
                    aux1 = $v0;
                }
                if (in1.equals($v1.getNome())) {
                    j = 3;
                    aux1 = $v1;
                }
                if (in1.equals($a0.getNome())) {
                    j = 4;
                    aux1 = $a0;
                }
                if (in1.equals($a1.getNome())) {
                    j = 5;
                    aux1 = $a1;
                }
                if (in1.equals($a2.getNome())) {
                    j = 6;
                    aux1 = $a2;
                }
                if (in1.equals($a3.getNome())) {
                    j = 7;
                    aux1 = $a3;
                }
                if (in1.equals($t0.getNome())) {
                    j = 8;
                    aux1 = $t0;
                }
                if (in1.equals($t1.getNome())) {
                    j = 9;
                    aux1 = $t1;
                }
                if (in1.equals($t2.getNome())) {
                    j = 10;
                    aux1 = $t2;
                }
                if (in1.equals($t3.getNome())) {
                    j = 11;
                    aux1 = $t3;
                }
                if (in1.equals($t4.getNome())) {
                    j = 12;
                    aux1 = $t4;
                }
                if (in1.equals($t5.getNome())) {
                    j = 13;
                    aux1 = $t5;
                }
                if (in1.equals($t6.getNome())) {
                    j = 14;
                    aux1 = $t6;
                }
                if (in1.equals($t7.getNome())) {
                    j = 15;
                    aux1 = $t7;
                }
                if (in1.equals($s0.getNome())) {
                    j = 16;
                    aux1 = $s0;
                }
                if (in1.equals($s1.getNome())) {
                    j = 17;
                    aux1 = $s1;
                }
                if (in1.equals($s2.getNome())) {
                    j = 18;
                    aux1 = $s2;
                }
                if (in1.equals($s3.getNome())) {
                    j = 19;
                    aux1 = $s3;
                }
                if (in1.equals($s4.getNome())) {
                    j = 20;
                    aux1 = $s4;
                }
                if (in1.equals($s5.getNome())) {
                    j = 21;
                    aux1 = $s5;
                }
                if (in1.equals($s6.getNome())) {
                    j = 22;
                    aux1 = $s6;
                }
                if (in1.equals($s7.getNome())) {
                    j = 23;
                    aux1 = $s7;
                }
                if (in1.equals($t8.getNome())) {
                    j = 24;
                    aux1 = $t8;
                }
                if (in1.equals($t9.getNome())) {
                    j = 25;
                    aux1 = $t9;
                }
                if (in1.equals($k0.getNome())) {
                    j = 26;
                    aux1 = $k0;
                }
                if (in1.equals($k1.getNome())) {
                    j = 27;
                    aux1 = $k1;
                }
                if (in1.equals($gp.getNome())) {
                    j = 28;
                    aux1 = $gp;
                }
                if (in1.equals($sp.getNome())) {
                    j = 29;
                    aux1 = $sp;
                }
                if (in1.equals($fp.getNome())) {
                    j = 30;
                    aux1 = $fp;
                }
                if (in1.equals($ra.getNome())) {
                    j = 31;
                    aux1 = $ra;
                }
            } else if (opcode != null && in1 != null && in2 != null && in3 != null) {
                if (in1.equals($zero.getNome())) {
                    j = 0;
                    aux1 = $zero;
                }
                if (in1.equals($at.getNome())) {
                    j = 1;
                    aux1 = $at;
                }
                if (in1.equals($v0.getNome())) {
                    j = 2;
                    aux1 = $v0;
                }
                if (in1.equals($v1.getNome())) {
                    j = 3;
                    aux1 = $v1;
                }
                if (in1.equals($a0.getNome())) {
                    j = 4;
                    aux1 = $a0;
                }
                if (in1.equals($a1.getNome())) {
                    j = 5;
                    aux1 = $a1;
                }
                if (in1.equals($a2.getNome())) {
                    j = 6;
                    aux1 = $a2;
                }
                if (in1.equals($a3.getNome())) {
                    j = 7;
                    aux1 = $a3;
                }
                if (in1.equals($t0.getNome())) {
                    j = 8;
                    aux1 = $t0;
                }
                if (in1.equals($t1.getNome())) {
                    j = 9;
                    aux1 = $t1;
                }
                if (in1.equals($t2.getNome())) {
                    j = 10;
                    aux1 = $t2;
                }
                if (in1.equals($t3.getNome())) {
                    j = 11;
                    aux1 = $t3;
                }
                if (in1.equals($t4.getNome())) {
                    j = 12;
                    aux1 = $t4;
                }
                if (in1.equals($t5.getNome())) {
                    j = 13;
                    aux1 = $t5;
                }
                if (in1.equals($t6.getNome())) {
                    j = 14;
                    aux1 = $t6;
                }
                if (in1.equals($t7.getNome())) {
                    j = 15;
                    aux1 = $t7;
                }
                if (in1.equals($s0.getNome())) {
                    j = 16;
                    aux1 = $s0;
                }
                if (in1.equals($s1.getNome())) {
                    j = 17;
                    aux1 = $s1;
                }
                if (in1.equals($s2.getNome())) {
                    j = 18;
                    aux1 = $s2;
                }
                if (in1.equals($s3.getNome())) {
                    j = 19;
                    aux1 = $s3;
                }
                if (in1.equals($s4.getNome())) {
                    j = 20;
                    aux1 = $s4;
                }
                if (in1.equals($s5.getNome())) {
                    j = 21;
                    aux1 = $s5;
                }
                if (in1.equals($s6.getNome())) {
                    j = 22;
                    aux1 = $s6;
                }
                if (in1.equals($s7.getNome())) {
                    j = 23;
                    aux1 = $s7;
                }
                if (in1.equals($t8.getNome())) {
                    j = 24;
                    aux1 = $t8;
                }
                if (in1.equals($t9.getNome())) {
                    j = 25;
                    aux1 = $t9;
                }
                if (in1.equals($k0.getNome())) {
                    j = 26;
                    aux1 = $k0;
                }
                if (in1.equals($k1.getNome())) {
                    j = 27;
                    aux1 = $k1;
                }
                if (in1.equals($gp.getNome())) {
                    j = 28;
                    aux1 = $gp;
                }
                if (in1.equals($sp.getNome())) {
                    j = 29;
                    aux1 = $sp;
                }
                if (in1.equals($fp.getNome())) {
                    j = 30;
                    aux1 = $fp;
                }
                if (in1.equals($ra.getNome())) {
                    j = 31;
                    aux1 = $ra;
                }
                if (in2.equals($zero.getNome())) {
                    k = 0;
                    aux2 = $zero;
                }
                if (in2.equals($at.getNome())) {
                    k = 1;
                    aux2 = $at;
                }
                if (in2.equals($v0.getNome())) {
                    k = 2;
                    aux2 = $v0;
                }
                if (in2.equals($v1.getNome())) {
                    k = 3;
                    aux2 = $v1;
                }
                if (in2.equals($a0.getNome())) {
                    k = 4;
                    aux2 = $a0;
                }
                if (in2.equals($a1.getNome())) {
                    k = 5;
                    aux2 = $a1;
                }
                if (in2.equals($a2.getNome())) {
                    k = 6;
                    aux2 = $a2;
                }
                if (in2.equals($a3.getNome())) {
                    k = 7;
                    aux2 = $a3;
                }
                if (in2.equals($t0.getNome())) {
                    k = 8;
                    aux2 = $t0;
                }
                if (in2.equals($t1.getNome())) {
                    k = 9;
                    aux2 = $t1;
                }
                if (in2.equals($t2.getNome())) {
                    k = 10;
                    aux2 = $t2;
                }
                if (in2.equals($t3.getNome())) {
                    k = 11;
                    aux2 = $t3;
                }
                if (in2.equals($t4.getNome())) {
                    k = 12;
                    aux2 = $t4;
                }
                if (in2.equals($t5.getNome())) {
                    k = 13;
                    aux2 = $t5;
                }
                if (in2.equals($t6.getNome())) {
                    k = 14;
                    aux2 = $t6;
                }
                if (in2.equals($t7.getNome())) {
                    k = 15;
                    aux2 = $t7;
                }
                if (in2.equals($s0.getNome())) {
                    k = 16;
                    aux2 = $s0;
                }
                if (in2.equals($s1.getNome())) {
                    k = 17;
                    aux2 = $s1;
                }
                if (in2.equals($s2.getNome())) {
                    k = 18;
                    aux2 = $s2;
                }
                if (in2.equals($s3.getNome())) {
                    k = 19;
                    aux2 = $s3;
                }
                if (in2.equals($s4.getNome())) {
                    k = 20;
                    aux2 = $s4;
                }
                if (in2.equals($s5.getNome())) {
                    k = 21;
                    aux2 = $s5;
                }
                if (in2.equals($s6.getNome())) {
                    k = 22;
                    aux2 = $s6;
                }
                if (in2.equals($s7.getNome())) {
                    k = 23;
                    aux2 = $s7;
                }
                if (in2.equals($t8.getNome())) {
                    k = 24;
                    aux2 = $t8;
                }
                if (in2.equals($t9.getNome())) {
                    k = 25;
                    aux2 = $t9;
                }
                if (in2.equals($k0.getNome())) {
                    k = 26;
                    aux2 = $k0;
                }
                if (in2.equals($k1.getNome())) {
                    k = 27;
                    aux2 = $k1;
                }
                if (in2.equals($gp.getNome())) {
                    k = 28;
                    aux2 = $gp;
                }
                if (in2.equals($sp.getNome())) {
                    k = 29;
                    aux2 = $sp;
                }
                if (in2.equals($fp.getNome())) {
                    k = 30;
                    aux2 = $fp;
                }
                if (in2.equals($ra.getNome())) {
                    k = 31;
                    aux2 = $ra;
                }

                if (in3.equals($zero.getNome())) {
                    l = 0;
                    aux3 = $zero;
                }
                if (in3.equals($at.getNome())) {
                    l = 1;
                    aux3 = $at;
                }
                if (in3.equals($v0.getNome())) {
                    l = 2;
                    aux3 = $v0;
                }
                if (in3.equals($v1.getNome())) {
                    l = 3;
                    aux3 = $v1;
                }
                if (in3.equals($a0.getNome())) {
                    l = 4;
                    aux3 = $a0;
                }
                if (in3.equals($a1.getNome())) {
                    l = 5;
                    aux3 = $a1;
                }
                if (in3.equals($a2.getNome())) {
                    l = 6;
                    aux3 = $a2;
                }
                if (in3.equals($a3.getNome())) {
                    l = 7;
                    aux3 = $a3;
                }
                if (in3.equals($t0.getNome())) {
                    l = 8;
                    aux3 = $t0;
                }
                if (in3.equals($t1.getNome())) {
                    l = 9;
                    aux3 = $t1;
                }
                if (in3.equals($t2.getNome())) {
                    l = 10;
                    aux3 = $t2;
                }
                if (in3.equals($t3.getNome())) {
                    l = 11;
                    aux3 = $t3;
                }
                if (in3.equals($t4.getNome())) {
                    l = 12;
                    aux3 = $t4;
                }
                if (in3.equals($t5.getNome())) {
                    l = 13;
                    aux3 = $t5;
                }
                if (in3.equals($t6.getNome())) {
                    l = 14;
                    aux3 = $t6;
                }
                if (in3.equals($t7.getNome())) {
                    l = 15;
                    aux3 = $t7;
                }
                if (in3.equals($s0.getNome())) {
                    l = 16;
                    aux3 = $s0;
                }
                if (in3.equals($s1.getNome())) {
                    l = 17;
                    aux3 = $s1;
                }
                if (in3.equals($s2.getNome())) {
                    l = 18;
                    aux3 = $s2;
                }
                if (in3.equals($s3.getNome())) {
                    l = 19;
                    aux3 = $s3;
                }
                if (in3.equals($s4.getNome())) {
                    l = 20;
                    aux3 = $s4;
                }
                if (in3.equals($s5.getNome())) {
                    l = 21;
                    aux3 = $s5;
                }
                if (in3.equals($s6.getNome())) {
                    l = 22;
                    aux3 = $s6;
                }
                if (in3.equals($s7.getNome())) {
                    l = 23;
                    aux3 = $s7;
                }
                if (in3.equals($t8.getNome())) {
                    l = 24;
                    aux3 = $t8;
                }
                if (in3.equals($t9.getNome())) {
                    l = 25;
                    aux3 = $t9;
                }
                if (in3.equals($k0.getNome())) {
                    l = 26;
                    aux3 = $k0;
                }
                if (in3.equals($k1.getNome())) {
                    l = 27;
                    aux3 = $k1;
                }
                if (in3.equals($gp.getNome())) {
                    l = 28;
                    aux3 = $gp;
                }
                if (in3.equals($sp.getNome())) {
                    l = 29;
                    aux3 = $sp;
                }
                if (in3.equals($fp.getNome())) {
                    l = 30;
                    aux3 = $fp;
                }
                if (in3.equals($ra.getNome())) {
                    l = 31;
                    aux3 = $ra;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Digite uma entrada correta");
                textoEntrada.setText("");
            }
            if (pipeline == false) {
                if (opcode != null && in1 != null && in2 != null && in3 == null) {
                    uc.interpretador(opcode, aux1, Integer.parseInt(in2));
                    in1 = null;
                    in2 = null;
                    in3 = null;
                    programCounter += 1;
                } else if (opcode != null && in1 != null && in2 != null && in3 != null) {
                    uc.interpretador(opcode, aux1, aux2, aux3);
                    in1 = null;
                    in2 = null;
                    in3 = null;
                    programCounter += 1;
                } else {
                    JOptionPane.showMessageDialog(null, "Digite uma entrada correta");
                    textoEntrada.setText("");
                }
            } else {
                if (opcode != null && in1 != null && in2 != null && in3 != null && in4 != null && in5 != null && in6 == null) {
                    uc.interpretadorPipeline(opcode, aux1, Integer.parseInt(in2), in4, aux4, Integer.parseInt(in5));
                    in1 = null;
                    in2 = null;
                    in3 = null;
                    in4 = null;
                    in5 = null;
                    in6 = null;
                    programCounter += 2;
                } else if (opcode != null && in1 != null && in2 != null && in3 != null) {
                    uc.interpretadorPipeline(opcode, aux1, aux2, aux3, in4 ,aux4, aux5, aux6);
                    in1 = null;
                    in2 = null;
                    in3 = null;
                    in4 = null;
                    in5 = null;
                    in6 = null;
                    programCounter += 2;
                } else {
                    JOptionPane.showMessageDialog(null, "Digite uma entrada correta");
                    textoEntrada.setText("");
                }
            }
            if (j == 0) {
                $zero = aux1;
            } else if (j == 1) {
                $at = aux1;
            } else if (j == 2) {
                $v0 = aux1;
            } else if (j == 3) {
                $v1 = aux1;
            } else if (j == 4) {
                $a0 = aux1;
            } else if (j == 5) {
                $a1 = aux1;
            } else if (j == 6) {
                $a2 = aux1;
            } else if (j == 7) {
                $a3 = aux1;
            } else if (j == 8) {
                $t0 = aux1;
            } else if (j == 9) {
                $t1 = aux1;
            } else if (j == 10) {
                $t2 = aux1;
            } else if (j == 11) {
                $t3 = aux1;
            } else if (j == 12) {
                $t4 = aux1;
            } else if (j == 13) {
                $t5 = aux1;
            } else if (j == 14) {
                $t6 = aux1;
            } else if (j == 15) {
                $t7 = aux1;
            } else if (j == 16) {
                $s0 = aux1;
            } else if (j == 17) {
                $s1 = aux1;
            } else if (j == 18) {
                $s2 = aux1;
            } else if (j == 19) {
                $s3 = aux1;
            } else if (j == 20) {
                $s4 = aux1;
            } else if (j == 21) {
                $s5 = aux1;
            } else if (j == 22) {
                $s6 = aux1;
            } else if (j == 23) {
                $s7 = aux1;
            } else if (j == 24) {
                $t8 = aux1;
            } else if (j == 25) {
                $t9 = aux1;
            } else if (j == 26) {
                $k0 = aux1;
            } else if (j == 27) {
                $k1 = aux1;
            } else if (j == 28) {
                $gp = aux1;
            } else if (j == 29) {
                $sp = aux1;
            } else if (j == 30) {
                $fp = aux1;
            } else if (j == 31) {
                $ra = aux1;
            } else if (k == 0) {
                $zero = aux2;
            } else if (k == 1) {
                $at = aux2;
            } else if (k == 2) {
                $v0 = aux2;
            } else if (k == 3) {
                $v1 = aux2;
            } else if (k == 4) {
                $a0 = aux2;
            } else if (k == 5) {
                $a1 = aux2;
            } else if (k == 6) {
                $a2 = aux2;
            } else if (k == 7) {
                $a3 = aux2;
            } else if (k == 8) {
                $t0 = aux2;
            } else if (k == 9) {
                $t1 = aux2;
            } else if (k == 10) {
                $t2 = aux2;
            } else if (k == 11) {
                $t3 = aux2;
            } else if (k == 12) {
                $t4 = aux2;
            } else if (k == 13) {
                $t5 = aux2;
            } else if (k == 14) {
                $t6 = aux2;
            } else if (k == 15) {
                $t7 = aux2;
            } else if (k == 16) {
                $s0 = aux2;
            } else if (k == 17) {
                $s1 = aux2;
            } else if (k == 18) {
                $s2 = aux2;
            } else if (k == 19) {
                $s3 = aux2;
            } else if (k == 20) {
                $s4 = aux2;
            } else if (k == 21) {
                $s5 = aux2;
            } else if (k == 22) {
                $s6 = aux2;
            } else if (k == 23) {
                $s7 = aux2;
            } else if (k == 24) {
                $t8 = aux2;
            } else if (k == 25) {
                $t9 = aux2;
            } else if (k == 26) {
                $k0 = aux2;
            } else if (k == 27) {
                $k1 = aux2;
            } else if (k == 28) {
                $gp = aux2;
            } else if (k == 29) {
                $sp = aux2;
            } else if (k == 30) {
                $fp = aux2;
            } else if (k == 31) {
                $ra = aux2;
            } else if (l == 0) {
                $zero = aux3;
            } else if (l == 1) {
                $at = aux3;
            } else if (l == 2) {
                $v0 = aux3;
            } else if (l == 3) {
                $v1 = aux3;
            } else if (l == 4) {
                $a0 = aux3;
            } else if (l == 5) {
                $a1 = aux3;
            } else if (l == 6) {
                $a2 = aux3;
            } else if (l == 7) {
                $a3 = aux3;
            } else if (l == 8) {
                $t0 = aux3;
            } else if (l == 9) {
                $t1 = aux3;
            } else if (l == 10) {
                $t2 = aux3;
            } else if (l == 11) {
                $t3 = aux3;
            } else if (l == 12) {
                $t4 = aux3;
            } else if (l == 13) {
                $t5 = aux3;
            } else if (l == 14) {
                $t6 = aux3;
            } else if (l == 15) {
                $t7 = aux3;
            } else if (l == 16) {
                $s0 = aux3;
            } else if (l == 17) {
                $s1 = aux3;
            } else if (l == 18) {
                $s2 = aux3;
            } else if (l == 19) {
                $s3 = aux3;
            } else if (l == 20) {
                $s4 = aux3;
            } else if (l == 21) {
                $s5 = aux3;
            } else if (l == 22) {
                $s6 = aux3;
            } else if (l == 23) {
                $s7 = aux3;
            } else if (l == 24) {
                $t8 = aux3;
            } else if (l == 25) {
                $t9 = aux3;
            } else if (l == 26) {
                $k0 = aux3;
            } else if (l == 27) {
                $k1 = aux3;
            } else if (l == 28) {
                $gp = aux3;
            } else if (l == 29) {
                $sp = aux3;
            } else if (l == 30) {
                $fp = aux3;
            } else if (l == 31) {
                $ra = aux3;
            }
            atualizarTela();
        }


    }//GEN-LAST:event_textoEntradaActionPerformed

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        pipeline = checkBox.isSelected();
    }//GEN-LAST:event_checkBoxActionPerformed

    private void m16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m16ActionPerformed

    public void atualizarTela() {

        this.r0.setText("" + $zero.ver());
        this.r1.setText("" + $at.ver());
        this.r2.setText("" + $v0.ver());
        this.r3.setText("" + $v1.ver());
        this.r4.setText("" + $a0.ver());
        this.r5.setText("" + $a1.ver());
        this.r6.setText("" + $a2.ver());
        this.r7.setText("" + $a3.ver());
        this.r8.setText("" + $t0.ver());
        this.r9.setText("" + $t1.ver());
        this.r10.setText("" + $t2.ver());
        this.r11.setText("" + $t3.ver());
        this.r12.setText("" + $t4.ver());
        this.r13.setText("" + $t5.ver());
        this.r14.setText("" + $t6.ver());
        this.r15.setText("" + $t7.ver());
        this.r16.setText("" + $s0.ver());
        this.r17.setText("" + $s1.ver());
        this.r18.setText("" + $s2.ver());
        this.r19.setText("" + $s3.ver());
        this.r20.setText("" + $s4.ver());
        this.r21.setText("" + $s5.ver());
        this.r22.setText("" + $s6.ver());
        this.r23.setText("" + $s7.ver());
        this.r24.setText("" + $t8.ver());
        this.r25.setText("" + $t9.ver());
        this.r26.setText("" + $k0.ver());
        this.r27.setText("" + $k1.ver());
        this.r28.setText("" + $gp.ver());
        this.r29.setText("" + $sp.ver());
        this.r30.setText("" + $fp.ver());
        this.r31.setText("" + $ra.ver());
        this.m0.setText("" + memoria.ver(0));
        this.m1.setText("" + memoria.ver(1));
        this.m2.setText("" + memoria.ver(2));
        this.m3.setText("" + memoria.ver(3));
        this.m4.setText("" + memoria.ver(4));
        this.m5.setText("" + memoria.ver(5));
        this.m6.setText("" + memoria.ver(6));
        this.ac.setText("" + aux1.ver());
        this.pc.setText("" + programCounter);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nm1;
    private javax.swing.JTextField ac;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField m0;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m10;
    private javax.swing.JTextField m12;
    private javax.swing.JTextField m14;
    private javax.swing.JTextField m15;
    private javax.swing.JTextField m16;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JTextField m6;
    private javax.swing.JTextField m8;
    private javax.swing.JTextField n2m;
    private javax.swing.JTextField nm6;
    private javax.swing.JTextField pc;
    private javax.swing.JTextField r0;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r10;
    private javax.swing.JTextField r11;
    private javax.swing.JTextField r12;
    private javax.swing.JTextField r13;
    private javax.swing.JTextField r14;
    private javax.swing.JTextField r15;
    private javax.swing.JTextField r16;
    private javax.swing.JTextField r17;
    private javax.swing.JTextField r18;
    private javax.swing.JTextField r19;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r20;
    private javax.swing.JTextField r21;
    private javax.swing.JTextField r22;
    private javax.swing.JTextField r23;
    private javax.swing.JTextField r24;
    private javax.swing.JTextField r25;
    private javax.swing.JTextField r26;
    private javax.swing.JTextField r27;
    private javax.swing.JTextField r28;
    private javax.swing.JTextField r29;
    private javax.swing.JTextField r3;
    private javax.swing.JTextField r30;
    private javax.swing.JTextField r31;
    private javax.swing.JTextField r4;
    private javax.swing.JTextField r5;
    private javax.swing.JTextField r6;
    private javax.swing.JTextField r7;
    private javax.swing.JTextField r8;
    private javax.swing.JTextField r9;
    private javax.swing.JTextField textoEntrada;
    // End of variables declaration//GEN-END:variables
}
